import { cn } from '@/lib/utils';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Nav } from '@/components/ui/nav';
import { Footer } from '@/components/sections/footer';
import { ContactSection } from '@/components/sections/contact-section';
import { Toaster } from '@/components/ui/toaster';
import { PageTransition } from '@/components/page-transition/page-transition';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="theme-color" content="#8000FF" />
      </head>
      <body
        className={cn(
          inter.className,
          'bg-dark text-white min-h-screen flex flex-col',
        )}
      >
        <Toaster />
        <PageTransition />
        <header className="sticky top-0 z-50">
          <Nav />
        </header>
        <div className="max-w-[1200px] mx-auto flex flex-col px-7 lg:px-14 flex-1 justify-center">
          {children}
          <ContactSection />
        </div>
        <Footer />
      </body>
    </html>
  );
}
